apiVersion: v1
kind: Namespace
metadata:
  name: ultra-dex
  labels:
    name: ultra-dex
    app.kubernetes.io/name: ultra-dex
    app.kubernetes.io/version: '6.0.0'
    app.kubernetes.io/managed-by: kubectl
