import chalk from 'chalk';
import fs from 'fs/promises';
import path from 'path';
import { validateSafePath } from '../utils/validation.js';
import { pathExists } from '../utils/files.js';
import { githubWebUrl } from '../config/urls.js';
import { runQualityScan } from '../quality/scanner.js';

export function registerAuditCommand(program) {
  program
    .command('audit')
    .description('Comprehensive project audit for completeness, quality, and security')
    .option('-d, --dir <directory>', 'Project directory to audit', '.')
    .option('--report', 'Generate a detailed JSON report')
    .option('--fix', 'Attempt to fix missing documentation files')
    .action(async (options) => {
      console.log(chalk.cyan('\n🔍 Ultra-Dex Project Audit\n'));

      const dirValidation = validateSafePath(options.dir, 'Project directory');
      if (dirValidation !== true) {
        console.log(chalk.red(dirValidation));
        process.exit(1);
      }

      const projectDir = path.resolve(options.dir);
      
      if (options.fix) {
          console.log(chalk.yellow('🛠️  Running auto-fixes...\n'));
          const missingFiles = ['QUICK-START.md', 'IMPLEMENTATION-PLAN.md', 'CONTEXT.md'];
          for (const file of missingFiles) {
              const fullPath = path.join(projectDir, file);
              try {
                  await fs.access(fullPath);
              } catch {
                  console.log(chalk.gray(`   Creating ${file}...`));
                  await fs.writeFile(fullPath, `# ${file.replace('.md', '')}\n\nGenerated by ultra-dex audit --fix\n`);
              }
          }
          console.log(chalk.green('\n✅ Auto-fixes complete.\n'));
      }

      let score = 0;
      let maxScore = 0;
      const results = [];

      // --- DOCUMENTATION AUDIT ---
      async function checkFile(filePath, description, points) {
        maxScore += points;
        try {
          const content = await fs.readFile(path.join(projectDir, filePath), 'utf-8');
          if (content.trim().length >= 2) {
            score += points;
            results.push({ category: 'Docs', status: '✅', item: description, points: `+${points}` });
            return content;
          } else {
            results.push({ category: 'Docs', status: '⚠️', item: `${description} (empty)`, points: '0' });
            return null;
          }
        } catch {
          results.push({ category: 'Docs', status: '❌', item: `${description} (Missing)`, points: '0' });
          return null;
        }
      }

      function hasSection(content, sectionName, points) {
        maxScore += points;
        if (content && content.toLowerCase().includes(sectionName.toLowerCase())) {
          score += points;
          results.push({ category: 'Docs', status: '✅', item: `Has ${sectionName}`, points: `+${points}` });
          return true;
        } else {
          results.push({ category: 'Docs', status: '❌', item: `Missing ${sectionName}`, points: '0' });
          return false;
        }
      }

      console.log(chalk.bold('📊 STRUCTURE AUDIT\n'));

      const quickStart = await checkFile('QUICK-START.md', 'QUICK-START.md', 10);
      const context = await checkFile('CONTEXT.md', 'CONTEXT.md', 5);
      const implPlan = await checkFile('IMPLEMENTATION-PLAN.md', 'IMPLEMENTATION-PLAN.md', 5);
      const readme = await checkFile('README.md', 'README.md', 5);
      await checkFile('package.json', 'package.json', 5);

      if (readme && readme.split('\n').length > 100) {
          score += 5;
          maxScore += 5;
          results.push({ category: 'Docs', status: '✅', item: 'Detailed README (>100 lines)', points: '+5' });
      }

      try {
          const hasSrc = await pathExists(path.join(projectDir, 'src'), 'dir');
          const hasLib = await pathExists(path.join(projectDir, 'lib'), 'dir');
          const hasCli = await pathExists(path.join(projectDir, 'cli'), 'dir');
          
          if (hasSrc || hasLib || hasCli) {
              const folderName = hasSrc ? 'src/' : (hasLib ? 'lib/' : 'cli/');
              score += 5;
              maxScore += 5;
              results.push({ category: 'Docs', status: '✅', item: `${folderName} folder exists`, points: '+5' });
              console.log(chalk.green(`  ✅ ${folderName} folder present`));
          } else {
              throw new Error('No source folder found');
          }
      } catch {
          maxScore += 5;
          results.push({ category: 'Docs', status: '❌', item: 'src/ or lib/ folder (Missing)', points: '0' });
          console.log(chalk.red('  ❌ src/ or lib/ folder missing'));
      }

      if (quickStart) {
        hasSection(quickStart, 'idea', 5);
        hasSection(quickStart, 'problem', 5);
        hasSection(quickStart, 'mvp', 5);
        hasSection(quickStart, 'tech stack', 10);
        hasSection(quickStart, 'feature', 5);
      }

      // --- SECURITY AUDIT ---
      console.log(chalk.bold('\n🛡️  SECURITY SCAN\n'));
      
      const scanResults = await runQualityScan(projectDir);
      const scanMaxPoints = 50;
      maxScore += scanMaxPoints;
      
      let codeScore = scanMaxPoints;
      const issues = [];

      scanResults.details.forEach(issue => {
          if (issue.severity === 'critical') codeScore -= 5;
          else if (issue.severity === 'error') codeScore -= 3;
          else if (issue.severity === 'warning') codeScore -= 1;
          issues.push(issue);
      });
      codeScore = Math.max(0, codeScore);
      score += codeScore;

      // Special check for .env.example (for test compatibility)
      try {
          await fs.access(path.join(projectDir, '.env.example'));
          console.log(chalk.green('  ✅ .env.example present'));
      } catch {
          console.log(chalk.yellow('  ⚠️  .env.example missing'));
      }

      if (scanResults.failed === 0 && scanResults.warnings === 0) {
          console.log(chalk.green('  ✅ No issues found. Clean code!'));
      } else {
          issues.slice(0, 5).forEach(issue => {
              const icon = issue.severity === 'critical' || issue.severity === 'error' ? '❌' : '⚠️';
              console.log(`  ${icon} [${issue.severity.toUpperCase()}] ${issue.file}: ${issue.message}`);
          });
      }

      // --- RESULTS ---
      console.log(chalk.bold('\nAudit Results:\n'));
      results.forEach(r => {
        const statusColor = r.status === '✅' ? chalk.green : r.status === '❌' ? chalk.red : chalk.yellow;
        console.log(`  ${statusColor(r.status)} [${r.category}] ${r.item} ${chalk.gray(r.points)}`);
      });

      const percentage = Math.round((score / maxScore) * 100);

      console.log('\n' + chalk.bold('─'.repeat(50)));
      console.log(chalk.bold(`\nScore: ${score}/${maxScore} (${percentage}%)\n`));

      let grade, gradeColor, message;
      if (percentage >= 90) {
        grade = 'A';
        gradeColor = chalk.green;
        message = 'Excellent! Your project is well-documented and secure.';
      } else if (percentage >= 75) {
        grade = 'B';
        gradeColor = chalk.green;
        message = 'Good! A few improvements needed.';
      } else if (percentage >= 60) {
        grade = 'C';
        gradeColor = chalk.yellow;
        message = 'Fair. Address critical issues and documentation gaps.';
      } else if (percentage >= 40) {
        grade = 'D';
        gradeColor = chalk.yellow;
        message = 'Needs work. Focus on structure and basic quality.';
      } else {
        grade = 'F';
        gradeColor = chalk.red;
        message = 'Run "npx ultra-dex init" and fix critical errors.';
      }

      console.log(gradeColor(`Grade: ${grade}`));
      console.log(chalk.gray(message));

      if (options.report) {
          const report = {
              timestamp: new Date().toISOString(),
              score,
              maxScore,
              percentage,
              grade,
              results,
              scanDetails: scanResults.details
          };
          const reportPath = path.join(projectDir, 'audit-report.json');
          await fs.writeFile(reportPath, JSON.stringify(report, null, 2));
          console.log(chalk.blue(`\n📝 Report saved to: ${reportPath}`));
      }

      const missing = results.filter(r => r.status === '❌');
      if (missing.length > 0 || issues.length > 0) {
        console.log(chalk.bold('\n📋 Action Items:\n'));
        missing.slice(0, 3).forEach(m => {
          console.log(chalk.cyan(`  → Add ${m.item.replace(' (missing)', '')}`));
        });
        if (issues.length > 0) {
            console.log(chalk.cyan(`  → Fix ${issues.length} code issues (run 'ultra-dex validate --scan')`));
        }
      }

      console.log(`\n${chalk.gray(`Learn more: ${githubWebUrl()}`)}\n`);
    });
}
