/**
 * ultra-dex generate command
 * Generates a full 34-section implementation plan from an idea using AI
 */

import chalk from 'chalk';
import ora from 'ora';
import inquirer from 'inquirer';
import fs from 'fs/promises';
import path from 'path';
import { createProvider, getDefaultProvider, checkConfiguredProviders } from '../providers/index.js';
import { SYSTEM_PROMPT, generateUserPrompt } from '../templates/prompts/generate-plan.js';

export function registerGenerateCommand(program) {
  program
    .command('generate [idea]')
    .description('Generate a full implementation plan from an idea using AI')
    .option('-p, --provider <provider>', 'AI provider (claude, openai, gemini)')
    .option('-m, --model <model>', 'Specific model to use')
    .option('-o, --output <directory>', 'Output directory', '.')
    .option('-k, --key <apiKey>', 'API key (or use environment variable)')
    .option('--stream', 'Stream output in real-time', true)
    .option('--no-stream', 'Disable streaming')
    .action(async (idea, options) => {
      console.log(chalk.cyan('\n🚀 Ultra-Dex Plan Generator\n'));

      // Check configured providers
      const configured = checkConfiguredProviders();
      const hasProvider = configured.some(p => p.configured) || options.key;

      if (!hasProvider) {
        console.log(chalk.yellow('⚠️  No AI provider configured.\n'));
        console.log(chalk.white('Set one of these environment variables:'));
        configured.forEach(p => {
          console.log(chalk.gray(`  export ${p.envKey}=your-key-here`));
        });
        console.log(chalk.white('\nOr use --key option:'));
        console.log(chalk.gray('  npx ultra-dex generate "your idea" --key sk-...\n'));
        return;
      }

      // Get idea if not provided
      if (!idea) {
        const answers = await inquirer.prompt([
          {
            type: 'input',
            name: 'idea',
            message: 'Describe your SaaS idea:',
            validate: input => input.trim().length > 10 || 'Please provide a more detailed description',
          },
        ]);
        idea = answers.idea;
      }

      // Select provider
      const providerId = options.provider || getDefaultProvider();
      if (!providerId) {
        console.log(chalk.red('No provider available. Set an API key.'));
        return;
      }

      console.log(chalk.gray(`Using provider: ${providerId}`));
      console.log(chalk.gray(`Idea: "${idea}"\n`));

      // Create provider instance
      let provider;
      try {
        provider = createProvider(providerId, {
          apiKey: options.key,
          model: options.model,
          maxTokens: 16000, // Large output for full plan
        });
      } catch (err) {
        console.log(chalk.red(`Error: ${err.message}`));
        return;
      }

      // Generate the plan
      const spinner = ora('Generating your implementation plan...').start();
      const startTime = Date.now();

      try {
        let result;
        let planContent = '';

        if (options.stream) {
          spinner.stop();
          console.log(chalk.cyan('📝 Generating plan:\n'));
          console.log(chalk.gray('─'.repeat(60)));

          result = await provider.generateStream(
            SYSTEM_PROMPT,
            generateUserPrompt(idea),
            (chunk) => {
              process.stdout.write(chunk);
              planContent += chunk;
            }
          );

          console.log(chalk.gray('\n' + '─'.repeat(60)));
        } else {
          result = await provider.generate(SYSTEM_PROMPT, generateUserPrompt(idea));
          planContent = result.content;
          spinner.succeed('Plan generated!');
        }

        // Calculate stats
        const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
        const cost = provider.estimateCost(result.usage.inputTokens, result.usage.outputTokens);

        // Save the plan
        const outputDir = path.resolve(options.output);
        await fs.mkdir(outputDir, { recursive: true });

        const planPath = path.join(outputDir, 'IMPLEMENTATION-PLAN.md');
        const contextPath = path.join(outputDir, 'CONTEXT.md');
        const quickStartPath = path.join(outputDir, 'QUICK-START.md');

        // Add header to plan
        const header = `# Implementation Plan

> Generated by Ultra-Dex on ${new Date().toISOString().split('T')[0]}
> Idea: "${idea}"

---

`;
        await fs.writeFile(planPath, header + planContent);

        // Generate CONTEXT.md
        const contextContent = `# Project Context

## Overview
${idea}

## Generated
- Date: ${new Date().toISOString().split('T')[0]}
- Provider: ${provider.getName()}
- Model: ${provider.model}

## Files
- IMPLEMENTATION-PLAN.md - Full 34-section plan
- QUICK-START.md - Quick reference
- CONTEXT.md - This file

## Usage
Provide this context to any AI agent:
\`\`\`
Act as @Backend. Read CONTEXT.md and IMPLEMENTATION-PLAN.md first.
Task: [your task]
\`\`\`
`;
        await fs.writeFile(contextPath, contextContent);

        // Generate QUICK-START.md
        const quickStartContent = `# Quick Start

## Your Idea
${idea}

## Next Steps

1. **Review the plan**: Open IMPLEMENTATION-PLAN.md
2. **Load into AI**: Copy CONTEXT.md to your AI tool
3. **Start building**: Use \`npx ultra-dex build\` or paste prompts

## Useful Commands

\`\`\`bash
npx ultra-dex build              # Start AI-assisted build
npx ultra-dex review             # Check code against plan
npx ultra-dex serve              # Serve context via HTTP
npx ultra-dex agents             # List available agents
\`\`\`

## Agent Quick Start

\`\`\`
@Planner - Break down tasks
@Backend - API endpoints
@Frontend - UI components
@Database - Schema design
@Auth - Authentication
@Testing - Write tests
\`\`\`
`;
        await fs.writeFile(quickStartPath, quickStartContent);

        // Print summary
        console.log(chalk.green('\n✅ Plan generated successfully!\n'));
        console.log(chalk.white('Files created:'));
        console.log(chalk.gray(`  📄 ${planPath}`));
        console.log(chalk.gray(`  📄 ${contextPath}`));
        console.log(chalk.gray(`  📄 ${quickStartPath}`));

        console.log(chalk.white('\nStats:'));
        console.log(chalk.gray(`  ⏱️  Time: ${elapsed}s`));
        console.log(chalk.gray(`  📊 Tokens: ${result.usage.inputTokens} in / ${result.usage.outputTokens} out`));
        console.log(chalk.gray(`  💰 Cost: ~$${cost.total.toFixed(4)}`));

        console.log(chalk.cyan('\n📋 Next steps:'));
        console.log(chalk.white('  1. Review IMPLEMENTATION-PLAN.md'));
        console.log(chalk.white('  2. Run: npx ultra-dex build'));
        console.log(chalk.white('  3. Start coding with AI agents\n'));

      } catch (err) {
        spinner.fail('Generation failed');
        console.log(chalk.red(`\nError: ${err.message}`));

        if (err.message.includes('API')) {
          console.log(chalk.yellow('\nTip: Check your API key and try again.'));
        }
      }
    });
}

export default { registerGenerateCommand };
