import fs from 'fs/promises';
import path from 'path';
import chalk from 'chalk';

export async function loadState() {
  try {
    const content = await fs.readFile(path.resolve(process.cwd(), '.ultra/state.json'), 'utf8');
    return JSON.parse(content);
  } catch (error) {
    console.error(chalk.red('Failed to load .ultra/state.json. Is the project initialized?'));
    return null;
  }
}

export async function saveState(state) {
  try {
    await fs.mkdir(path.resolve(process.cwd(), '.ultra'), { recursive: true });
    await fs.writeFile(
      path.resolve(process.cwd(), '.ultra/state.json'), 
      JSON.stringify(state, null, 2)
    );
    return true;
  } catch (error) {
    console.error(chalk.red('Failed to save state:'), error);
    return false;
  }
}

export function generateMarkdown(state) {
  const { project, phases } = state;
  let md = `# ${project.name} - Implementation Plan\n\n`;
  md += `> **Generated by Ultra-Dex Core**\n`;
  md += `> Version: ${project.version}\n`;
  md += `> Mode: ${project.mode}\n\n`;

  md += `## 🚀 Execution Phases\n\n`;

  phases.forEach(phase => {
    const statusIcon = phase.status === 'completed' ? '✅' : phase.status === 'in_progress' ? '🔄' : '⏳';
    md += `### ${statusIcon} ${phase.name}\n\n`;
    
    if (phase.steps && phase.steps.length > 0) {
      phase.steps.forEach(step => {
        const stepIcon = step.status === 'completed' ? '- [x]' : '- [ ]';
        md += `${stepIcon} **${step.id}**: ${step.task}\n`;
      });
    } else {
      md += `_No steps defined for this phase._\n`;
    }
    md += `\n`;
  });

  md += `## 🤖 Agent Registry\n\n`;
  if (state.agents && state.agents.registry) {
    state.agents.registry.forEach(agent => {
      const active = state.agents.active.includes(agent) ? '(Active)' : '';
      md += `- ${agent} ${active}\n`;
    });
  }

  md += `\n---\n`;
  md += `*This file is strictly read-only. Edit .ultra/state.json to update.*`;

  return md;
}

export function registerPlanCommand(program) {
  program
    .command('plan')
    .description('Generate IMPLEMENTATION-PLAN.md from state.json')
    .action(async () => {
      const state = await loadState();
      if (!state) return;

      console.log(chalk.blue(`Generating plan for ${state.project.name}...`));
      
      const markdown = generateMarkdown(state);
      await fs.writeFile(path.resolve(process.cwd(), 'IMPLEMENTATION-PLAN.md'), markdown);
      
      console.log(chalk.green(`✅ IMPLEMENTATION-PLAN.md generated successfully.`));
    });
}
