var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __decorateClass = (decorators, target, key, kind) => {
  var result = kind > 1 ? void 0 : kind ? __getOwnPropDesc(target, key) : target;
  for (var i = decorators.length - 1, decorator; i >= 0; i--)
    if (decorator = decorators[i])
      result = (kind ? decorator(target, key, result) : decorator(result)) || result;
  if (kind && result)
    __defProp(target, key, result);
  return result;
};
import { singleton } from "tsyringe";
import { agentOrchestrator } from '../orchestration/index.js';
import fs from "fs/promises";
import path from "path";
import chalk from "chalk";
let IntelligentScaffolder = class {
  async scaffold(objective, targetDir) {
    console.log(chalk.cyan(`\u{1F680} Intelligent Scaffolding: ${objective}`));
    const archResult = await agentOrchestrator.executeTask(
      `Generate a file structure list for a project with this goal: ${objective}. Output ONLY a JSON array of file paths.`,
      { requiredCapabilities: ["architecture"] }
    );
    let files = [];
    try {
      const match = archResult.output.match(/\[.*\]/s);
      files = match ? JSON.parse(match[0]) : ["README.md", "src/index.js", ".env.example"];
    } catch {
      files = ["README.md", "src/index.js", ".env.example"];
    }
    for (const file of files) {
      const fullPath = path.join(targetDir, file);
      try {
        await fs.mkdir(path.dirname(fullPath), { recursive: true });
        await fs.writeFile(fullPath, `// Generated by Ultra-Dex Meta-Layer
// Objective: ${objective}`, "utf8");
        console.log(chalk.gray(`  + ${file}`));
      } catch (e) {
        console.error(chalk.red(`  ! Failed to create ${file}: ${e.message}`));
      }
    }
    console.log(chalk.green("\u2705 Intelligent Scaffold Complete."));
  }
};
IntelligentScaffolder = __decorateClass([
  singleton()
], IntelligentScaffolder);
const scaffolder = new IntelligentScaffolder();
export {
  IntelligentScaffolder,
  scaffolder
};
