// Copyright (c) 2026 Ultra-Dex
import { agentOrchestrator } from '../orchestration/index.js';
import fs from 'fs/promises';
import path from 'path';
import chalk from 'chalk';

export class IntelligentScaffolder {
  async scaffold(objective, targetDir) {
    console.log(chalk.cyan(`🚀 Intelligent Scaffolding: ${objective}`));
    
    // 1. Ask Architect for Structure
    const archResult = await agentOrchestrator.executeTask(
      `Generate a file structure list for a project with this goal: ${objective}. Output ONLY a JSON array of file paths.`,
      { requiredCapabilities: ['architecture'] }
    );

    let files = [];
    try {
      // Find JSON array in output
      const match = archResult.output.match(/\[.*\]/s);
      files = match ? JSON.parse(match[0]) : ['README.md', 'src/index.js', '.env.example'];
    } catch {
      files = ['README.md', 'src/index.js', '.env.example']; // Fallback
    }

    // 2. Create Files
    for (const file of files) {
      const fullPath = path.join(targetDir, file);
      try {
        await fs.mkdir(path.dirname(fullPath), { recursive: true });
        await fs.writeFile(fullPath, `// Generated by Ultra-Dex Meta-Layer\n// Objective: ${objective}`, 'utf8');
        console.log(chalk.gray(`  + ${file}`));
      } catch (e) {
        console.error(chalk.red(`  ! Failed to create ${file}: ${e.message}`));
      }
    }

    console.log(chalk.green('✅ Intelligent Scaffold Complete.'));
  }
}

export const scaffolder = new IntelligentScaffolder();

