// Copyright (c) 2026 Ultra-Dex

/**
 * Cursor IDE Plugin for Ultra-Dex
 * Provides "Import from Ultra-Dex" functionality
 */

import fs from 'fs';
import path from 'path';

export class CursorPlugin {
  constructor(options = {}) {
    this.workspacePath = options.workspacePath || process.cwd();
  }

  /**
   * Generate .cursorrules file for Cursor IDE
   */
  generateCursorRules() {
    const contextPath = path.join(this.workspacePath, 'CONTEXT.md');
    const planPath = path.join(this.workspacePath, 'IMPLEMENTATION-PLAN.md');

    let context = '';
    let plan = '';

    if (fs.existsSync(contextPath)) {
      context = fs.readFileSync(contextPath, 'utf8').slice(0, 4000);
    }

    if (fs.existsSync(planPath)) {
      plan = fs.readFileSync(planPath, 'utf8').slice(0, 4000);
    }

    const rules = `# Ultra-Dex Cursor Rules
# Auto-generated by Ultra-Dex CLI

## Project Context
${context || 'No CONTEXT.md found. Run `ultra-dex init` to create one.'}

## Implementation Plan
${plan || 'No IMPLEMENTATION-PLAN.md found.'}

## Agent Guidelines

When assisting with this project:
1. Always reference CONTEXT.md for project understanding
2. Follow the patterns in IMPLEMENTATION-PLAN.md
3. Use the 21-step verification before completing tasks
4. Maintain consistency with existing code patterns

## Code Style
- Follow existing formatting conventions
- Use TypeScript for new code when applicable
- Write tests for new functionality
- Document complex logic

## Available Agents
Use @agent mentions to invoke specialized assistants:
- @CTO - Strategic decisions
- @Backend - API development
- @Frontend - UI/UX work
- @Security - Security audits
- @DevOps - Infrastructure
`;

    const outputPath = path.join(this.workspacePath, '.cursorrules');
    fs.writeFileSync(outputPath, rules);

    return outputPath;
  }

  /**
   * Import agents from Ultra-Dex to Cursor composer
   */
  exportAgentsForComposer() {
    const agentsDir = path.join(this.workspacePath, 'agents');
    const agents = [];

    if (fs.existsSync(agentsDir)) {
      const files = fs.readdirSync(agentsDir).filter((f) => f.endsWith('.md'));

      for (const file of files) {
        const content = fs.readFileSync(path.join(agentsDir, file), 'utf8');
        const name = file.replace('.md', '').replace(/^\d+-/, '');

        agents.push({
          name,
          filename: file,
          prompt: content.slice(0, 2000),
        });
      }
    }

    return agents;
  }

  /**
   * Generate Cursor settings.json additions
   */
  generateCursorSettings() {
    return {
      'cursor.ai.customInstructions': `Always reference CONTEXT.md and IMPLEMENTATION-PLAN.md in this project. Follow Ultra-Dex 21-step verification.`,
      'cursor.ai.modelPreferences': {
        chat: 'claude-3-sonnet',
        composer: 'claude-3-opus',
      },
    };
  }
}

/**
 * Windsurf (Cascade) Plugin for Ultra-Dex
 */
export class WindsurfPlugin {
  constructor(options = {}) {
    this.workspacePath = options.workspacePath || process.cwd();
  }

  /**
   * Generate Windsurf rules file
   */
  generateWindsurfRules() {
    const rules = {
      version: '1.0',
      name: 'Ultra-Dex Project',
      rules: [
        {
          type: 'context',
          source: 'CONTEXT.md',
          priority: 'high',
        },
        {
          type: 'context',
          source: 'IMPLEMENTATION-PLAN.md',
          priority: 'high',
        },
        {
          type: 'pattern',
          description: 'Follow existing code patterns in the codebase',
        },
      ],
      agents: this.exportAgents(),
    };

    const outputPath = path.join(this.workspacePath, '.windsurf/rules.json');
    const dir = path.dirname(outputPath);

    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(outputPath, JSON.stringify(rules, null, 2));
    return outputPath;
  }

  exportAgents() {
    const agentsDir = path.join(this.workspacePath, 'agents');
    const agents = [];

    if (fs.existsSync(agentsDir)) {
      const files = fs.readdirSync(agentsDir).filter((f) => f.endsWith('.md'));

      for (const file of files.slice(0, 10)) {
        const name = file.replace('.md', '').replace(/^\d+-/, '');
        agents.push({ name, file: `agents/${file}` });
      }
    }

    return agents;
  }
}

/**
 * Cline/Continue.dev Plugin for Ultra-Dex
 */
export class ClinePlugin {
  constructor(options = {}) {
    this.workspacePath = options.workspacePath || process.cwd();
  }

  /**
   * Generate Continue.dev config
   */
  generateContinueConfig() {
    const config = {
      name: 'Ultra-Dex',
      tabAutocompleteModel: {
        title: 'Fast',
        provider: 'anthropic',
        model: 'claude-3-haiku',
      },
      models: [
        {
          title: 'Claude Sonnet',
          provider: 'anthropic',
          model: 'claude-3-sonnet',
        },
      ],
      contextProviders: [
        { name: 'file', params: {} },
        { name: 'code', params: {} },
        { name: 'docs', params: {} },
        {
          name: 'folder',
          params: {
            path: 'agents',
            description: 'Ultra-Dex AI Agents',
          },
        },
      ],
      slashCommands: [
        {
          name: 'context',
          description: 'Load Ultra-Dex context',
          command: 'cat CONTEXT.md',
        },
        {
          name: 'plan',
          description: 'Load implementation plan',
          command: 'cat IMPLEMENTATION-PLAN.md',
        },
        {
          name: 'agent',
          description: 'Load agent prompt',
          command: 'cat agents/$1.md',
        },
      ],
    };

    const outputPath = path.join(this.workspacePath, '.continue/config.json');
    const dir = path.dirname(outputPath);

    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(outputPath, JSON.stringify(config, null, 2));
    return outputPath;
  }
}

/**
 * Generate all AI tool configs
 */
export async function generateAllPluginConfigs(workspacePath) {
  const results = [];

  const cursor = new CursorPlugin({ workspacePath });
  results.push({
    tool: 'Cursor',
    path: cursor.generateCursorRules(),
  });

  const windsurf = new WindsurfPlugin({ workspacePath });
  results.push({
    tool: 'Windsurf',
    path: windsurf.generateWindsurfRules(),
  });

  const cline = new ClinePlugin({ workspacePath });
  results.push({
    tool: 'Continue.dev',
    path: cline.generateContinueConfig(),
  });

  return results;
}

export default {
  CursorPlugin,
  WindsurfPlugin,
  ClinePlugin,
  generateAllPluginConfigs,
};

/**
 * Safe execution wrapper with error handling for ai-tools
 * @param {Function} fn - Async function to execute
 * @param {string} [context='ai-tools'] - Error context
 * @returns {Promise<*>} Result or null on error
 */
async function safeExecute(fn, context = 'ai-tools') {
  try {
    return await fn();
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error(`[${context}] Error: ${message}`);
    return null;
  }
}
