/**
 * LangGraph State Visualizer
 * Creates visual representations of agent workflow states
 */

import fs from 'fs/promises';
import path from 'path';
import { printInfo, printSuccess, printWarning, printError } from '../utils/output.js';
import chalk from 'chalk';
import { AppError } from '../utils/errors.js';

/**
 * Generate Mermaid diagram from state graph
 */
export function generateMermaidDiagram(graph) {
  const mermaid = [
    'graph TD',
    '  %% Ultra-Dex Agent Workflow State Diagram',
    '  %% Generated by Ultra-Dex LangGraph Visualizer',
    ''
  ];

  // Add nodes
  for (const [nodeId, node] of Object.entries(graph.nodes || {})) {
    const displayName = node.label || nodeId.replace(/([A-Z])/g, ' $1').trim();
    mermaid.push(`  ${nodeId}["${displayName}"]`);
  }

  // Add edges
  for (const [edgeId, edge] of Object.entries(graph.edges || {})) {
    const source = edge.source || edge.from;
    const target = edge.target || edge.to;
    const label = edge.label || '';
    
    if (source && target) {
      const arrow = label ? `-->|${label}|` : '-->';
      mermaid.push(`  ${source} ${arrow} ${target}`);
    }
  }

  // Add state information
  mermaid.push('');
  mermaid.push('  %% Current State Information');
  if (graph.currentState) {
    mermaid.push(`  %% Current Node: ${graph.currentState}`);
  }
  if (graph.completedNodes) {
    mermaid.push(`  %% Completed: ${graph.completedNodes.join(', ')}`);
  }

  return mermaid.join('\n');
}

/**
 * Generate ASCII visualization of state graph
 */
export function generateAsciiVisualization(graph) {
  let ascii = '';
  
  ascii += chalk.bold.blue('┌─────────────────────────────────────────────────────────┐\n');
  ascii += chalk.bold.blue('│                    AGENT WORKFLOW STATE                 │\n');
  ascii += chalk.bold.blue('└─────────────────────────────────────────────────────────┘\n\n');
  
  // Create a simple ASCII representation
  const nodes = Object.entries(graph.nodes || {});
  const edges = Object.entries(graph.edges || {});
  
  // Show nodes with status
  for (const [nodeId, node] of nodes) {
    const status = node.status || 'pending';
    const statusChar = {
      'completed': chalk.green('✓'),
      'running': chalk.yellow('↻'),
      'failed': chalk.red('✗'),
      'pending': chalk.gray('○')
    }[status] || chalk.gray('?');
    
    const displayName = node.label || nodeId.replace(/([A-Z])/g, ' $1').trim();
    ascii += `${statusChar} ${chalk.bold(displayName)}\n`;
    
    // Show any connected edges
    for (const [_, edge] of edges) {
      if (edge.source === nodeId) {
        const targetNode = nodes.find(([id, _]) => id === edge.target)?.[1];
        const targetName = targetNode?.label || edge.target;
        ascii += chalk.gray(`    └─→ ${targetName}\n`);
      }
    }
    ascii += '\n';
  }
  
  if (graph.currentState) {
    ascii += chalk.cyan(`📍 Current State: ${graph.currentState}\n`);
  }
  
  if (graph.completedNodes) {
    ascii += chalk.green(`✅ Completed: ${graph.completedNodes.join(', ')}\n`);
  }
  
  if (graph.failedNodes) {
    ascii += chalk.red(`❌ Failed: ${graph.failedNodes.join(', ')}\n`);
  }
  
  return ascii;
}

/**
 * Generate SVG from Mermaid diagram
 */
export async function generateSvgFromMermaid(mermaidCode) {
  // In a real implementation, this would use a library like @mermaid-js/mermaid-cli
  // For now, we'll return a placeholder SVG
  
  const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600">
  <rect width="100%" height="100%" fill="white"/>
  <text x="50%" y="50%" text-anchor="middle" dominant-baseline="middle" font-family="Arial" font-size="16">
    LangGraph State Visualization
  </text>
  <text x="50%" y="55%" text-anchor="middle" dominant-baseline="middle" font-family="monospace" font-size="12">
    Mermaid Diagram Generated
  </text>
</svg>`;

  return svg;
}

/**
 * Create state graph from agent workflow
 */
export function createStateGraph(agents, currentState = null) {
  const graph = {
    nodes: {},
    edges: {},
    currentState,
    completedNodes: [],
    failedNodes: [],
    metadata: {
      timestamp: new Date().toISOString(),
      agentCount: agents.length
    }
  };

  // Create nodes for each agent
  for (const agent of agents) {
    graph.nodes[agent.name] = {
      id: agent.name,
      label: agent.name.replace(/^@/, '').replace(/([A-Z])/g, ' $1').trim(),
      status: agent.status || 'pending',
      description: agent.description,
      tier: agent.tier
    };
    
    if (agent.status === 'completed') {
      graph.completedNodes.push(agent.name);
    } else if (agent.status === 'failed') {
      graph.failedNodes.push(agent.name);
    }
  }

  // Create edges based on agent dependencies/order
  for (let i = 0; i < agents.length - 1; i++) {
    const currentAgent = agents[i];
    const nextAgent = agents[i + 1];
    
    graph.edges[`${currentAgent.name}-${nextAgent.name}`] = {
      source: currentAgent.name,
      target: nextAgent.name,
      label: 'next'
    };
  }

  return graph;
}

/**
 * Export state graph in various formats
 */
export async function exportStateGraph(graph, format, outputPath) {
  let content;
  
  switch (format.toLowerCase()) {
    case 'mermaid':
      content = generateMermaidDiagram(graph);
      break;
    case 'svg':
      content = await generateSvgFromMermaid(generateMermaidDiagram(graph));
      break;
    case 'json':
      content = JSON.stringify(graph, null, 2);
      break;
    case 'ascii':
      content = generateAsciiVisualization(graph);
      break;
    default:
      throw new AppError(`Unsupported format: ${format}`, { code: 'UNSUPPORTED_FORMAT' });
  }
  
  // Write to file
  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, content);
  
  return {
    path: outputPath,
    format,
    size: Buffer.byteLength(content)
  };
}

/**
 * Visualize current swarm state
 */
export async function visualizeSwarmState(swarmState, options = {}) {
  try {
    printInfo(chalk.cyan.bold('\n🌐 LangGraph State Visualization\n'));
    
    // Create state graph from swarm state
    const graph = createStateGraph(
      swarmState.agents || [], 
      swarmState.currentAgent || null
    );
    
    if (options.ascii) {
      // Show ASCII visualization in terminal
      const ascii = generateAsciiVisualization(graph);
      printInfo(ascii);
    } else if (options.mermaid) {
      // Generate and show mermaid diagram
      const mermaidCode = generateMermaidDiagram(graph);
      printInfo(chalk.blue('Mermaid Diagram:\n'));
      printInfo(chalk.gray(mermaidCode));
      
      if (options.export) {
        const exportPath = options.export;
        await exportStateGraph(graph, 'mermaid', exportPath);
        printSuccess(chalk.green(`✅ Mermaid diagram exported to: ${exportPath}`));
      }
    } else if (options.svg) {
      // Generate SVG
      const svgPath = options.svg === true ? 'state-graph.svg' : options.svg;
      const result = await exportStateGraph(graph, 'svg', svgPath);
      printSuccess(chalk.green(`✅ SVG exported to: ${result.path}`));
    } else if (options.json) {
      // Generate JSON
      const jsonPath = options.json === true ? 'state-graph.json' : options.json;
      const result = await exportStateGraph(graph, 'json', jsonPath);
      printSuccess(chalk.green(`✅ JSON exported to: ${result.path}`));
    } else {
      // Default: show ASCII in terminal
      const ascii = generateAsciiVisualization(graph);
      printInfo(ascii);
      
      printInfo(chalk.gray('\nUse --mermaid, --svg, --json, or --ascii to export in different formats'));
    }
    
    return graph;
  } catch (error) {
    printError(chalk.red(`❌ Failed to visualize swarm state: ${error.message}`));
    throw error;
  }
}

/**
 * Register the graph command with Commander
 */
export function registerGraphCommand(program) {
  program
    .command('graph')
    .description('Visualize agent workflow state with LangGraph')
    .option('--ascii', 'Show ASCII visualization in terminal')
    .option('--mermaid', 'Generate Mermaid diagram')
    .option('--svg [path]', 'Generate SVG diagram (default: state-graph.svg)')
    .option('--json [path]', 'Export as JSON (default: state-graph.json)')
    .option('--export <path>', 'Export diagram to specified path')
    .option('--format <format>', 'Export format (mermaid, svg, json, ascii)', 'ascii')
    .action(async (options) => {
      try {
        // For now, we'll create a mock swarm state
        // In a real implementation, this would get the actual swarm state
        const mockSwarmState = {
          agents: [
            { name: '@planner', status: 'completed', description: 'Project planning', tier: '1-leadership' },
            { name: '@cto', status: 'completed', description: 'Architecture decisions', tier: '1-leadership' },
            { name: '@backend', status: 'running', description: 'Backend development', tier: '2-development' },
            { name: '@frontend', status: 'pending', description: 'Frontend development', tier: '2-development' },
            { name: '@testing', status: 'pending', description: 'Quality assurance', tier: '4-quality' }
          ],
          currentAgent: '@backend',
          progress: 40
        };
        
        await visualizeSwarmState(mockSwarmState, options);
      } catch (error) {
        printError(chalk.red(`\n❌ Graph command failed: ${error.message}`));
        process.exitCode = error.exitCode || 1;
        throw error;
      }
    });
}

export default {
  generateMermaidDiagram,
  generateAsciiVisualization,
  generateSvgFromMermaid,
  createStateGraph,
  exportStateGraph,
  visualizeSwarmState,
  registerGraphCommand
};