repos:
  - repo: local
    hooks:
      - id: ultra-dex-validate
        name: Ultra-Dex Validate
        entry: ultra-dex validate
        language: system
        pass_filenames: false
      - id: ultra-dex-align
        name: Ultra-Dex Align
        entry: ultra-dex align
        language: system
        pass_filenames: false
