#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = '/Users/srujansai/Desktop/Ultra-Dex';

function countLinesInDir(dir) {
  try {
    const result = execSync(
      `find "${dir}" -type f \\( -name "*.js" -o -name "*.cjs" -o -name "*.ts" \\) ! -path "*/node_modules/*" | xargs wc -l 2>/dev/null | tail -1`,
      { encoding: 'utf8' }
    );
    const match = result.match(/(\d+)\s+total/);
    return match ? parseInt(match[1]) : 0;
  } catch (e) {
    return 0;
  }
}

function getSubdirBreakdown(baseDir) {
  const dirs = fs.readdirSync(baseDir).filter(d => {
    const stat = fs.statSync(path.join(baseDir, d));
    return stat.isDirectory() && d !== 'node_modules';
  });
  
  const breakdown = [];
  for (const dir of dirs) {
    const fullPath = path.join(baseDir, dir);
    const lines = countLinesInDir(fullPath);
    breakdown.push({ dir, lines });
  }
  
  return breakdown.sort((a, b) => b.lines - a.lines);
}

console.log('📊 Counting lines of code...\n');

// src/core/ breakdown
const coreTotal = countLinesInDir(path.join(ROOT, 'src/core'));
const coreBreakdown = getSubdirBreakdown(path.join(ROOT, 'src/core'));

// apps/ breakdown
const appsTotal = countLinesInDir(path.join(ROOT, 'apps'));
const appsBreakdown = getSubdirBreakdown(path.join(ROOT, 'apps'));

// Generate report
const report = `# Codebase Size Report

**Generated:** ${new Date().toISOString().split('T')[0]}  
**Excludes:** node_modules directories

---

## Summary

| Directory | Lines of Code |
|-----------|---------------|
| src/core/ | ${coreTotal.toLocaleString()} |
| apps/ | ${appsTotal.toLocaleString()} |
| **Total** | **${(coreTotal + appsTotal).toLocaleString()}** |

---

## src/core/ Breakdown

| Subdirectory | Lines of Code |
|--------------|---------------|
${coreBreakdown.map(b => `| ${b.dir}/ | ${b.lines.toLocaleString()} |`).join('\n')}

**Total src/core/:** ${coreTotal.toLocaleString()} LOC

---

## apps/ Breakdown

| Subdirectory | Lines of Code |
|--------------|---------------|
${appsBreakdown.map(b => `| ${b.dir}/ | ${b.lines.toLocaleString()} |`).join('\n')}

**Total apps/:** ${appsTotal.toLocaleString()} LOC

---

## Top 50 Files by Line Count (src/core/)

\`\`\`
${execSync(`find src/core/ -type f \\( -name "*.js" -o -name "*.cjs" -o -name "*.ts" \\) ! -path "*/node_modules/*" | xargs wc -l 2>/dev/null | sort -rn | head -50`, { encoding: 'utf8', cwd: ROOT })}
\`\`\`

---

## Top 50 Files by Line Count (apps/)

\`\`\`
${execSync(`find apps/ -type f \\( -name "*.js" -o -name "*.ts" \\) ! -path "*/node_modules/*" | xargs wc -l 2>/dev/null | sort -rn | head -50`, { encoding: 'utf8', cwd: ROOT })}
\`\`\`

---

*Report generated by count-loc.cjs*
`;

// Write report
fs.writeFileSync(path.join(ROOT, 'upgrade/reports/codebase-size.md'), report);

console.log('✅ Report generated!\n');
console.log(`📄 Report saved to: upgrade/reports/codebase-size.md\n`);
console.log('═══════════════════════════════════════════════════════════\n');
console.log('SUMMARY:\n');
console.log(`   src/core/: ${coreTotal.toLocaleString()} LOC`);
console.log(`   apps/:     ${appsTotal.toLocaleString()} LOC`);
console.log(`   TOTAL:     ${(coreTotal + appsTotal).toLocaleString()} LOC\n`);
console.log('═══════════════════════════════════════════════════════════\n');
