// Copyright (c) 2026 Ultra-Dex

/**
 * ultra-dex github command
 * GitHub App integration for issue tracking, auto-PR creation, and CI/CD
 * This connects Ultra-Dex to the GitHub ecosystem for true automation
 */

import chalk from 'chalk';
import ora from 'ora';
import fs from 'fs/promises';
import path from 'path';
import { execFile } from 'child_process';
import { promisify } from 'util';
import inquirer from 'inquirer';

const execFileAsync = promisify(execFile);

async function runCommand(command, args) {
  if (typeof globalThis.mockExecFileFunction === 'function') {
    return globalThis.mockExecFileFunction(command, args);
  }
  return execFileAsync(command, args);
}

// ============================================================================
// GITHUB CONFIGURATION
// ============================================================================

export const GITHUB_CONFIG = {
  // State file for tracking synced issues
  stateFile: '.ultra-dex/github-sync.json',

  // Label mappings
  labelToAgent: {
    backend: '@Backend',
    frontend: '@Frontend',
    database: '@Database',
    auth: '@Auth',
    security: '@Security',
    testing: '@Testing',
    devops: '@DevOps',
    bug: '@Debugger',
    documentation: '@Documentation',
    performance: '@Performance',
  },

  // PR template
  prTemplate: `## Summary
{summary}

## Changes
{changes}

## Testing
{testing}

---
🤖 Generated by [Ultra-Dex](https://github.com/Srujan0798/Ultra-Dex) Agent Swarm
`,
};

// ============================================================================
// GITHUB CLI UTILITIES
// ============================================================================

/**
 * Check if GitHub CLI is installed and authenticated
 */
export async function checkGitHubCLI() {
  try {
    await runCommand('gh', ['--version']);
    const { stdout } = await runCommand('gh', ['auth', 'status']);
    return { installed: true, authenticated: stdout.includes('Logged in') };
  } catch (err) {
    if (err.message.includes('not found')) {
      return { installed: false, authenticated: false };
    }
    // gh auth status returns non-zero if not authenticated
    return { installed: true, authenticated: false };
  }
}

/**
 * Get current repository info
 */
export async function getRepoInfo() {
  try {
    const { stdout } = await runCommand('gh', ['repo', 'view', '--json', 'owner,name,url']);
    return JSON.parse(stdout);
  } catch {
    return null;
  }
}

/**
 * List open issues
 */
export async function listIssues(options = {}) {
  const { limit = 20, labels = [], state = 'open' } = options;

  const args = [
    'issue',
    'list',
    '--state',
    state,
    '--limit',
    String(limit),
    '--json',
    'number,title,labels,body,assignees,createdAt',
  ];

  if (labels.length > 0) {
    args.push('--label', labels.join(','));
  }

  const { stdout } = await runCommand('gh', args);
  return JSON.parse(stdout);
}

/**
 * Create a new issue
 */
export async function createIssue(title, body, options = {}) {
  const { labels = [], assignees = [] } = options;

  const args = ['issue', 'create', '--title', title, '--body', body];

  if (labels.length > 0) {
    args.push('--label', labels.join(','));
  }

  if (assignees.length > 0) {
    args.push('--assignee', assignees.join(','));
  }

  const { stdout } = await runCommand('gh', args);
  return stdout.trim();
}

/**
 * Create a pull request
 */
export async function createPullRequest(title, body, options = {}) {
  const { base = 'main', head, draft = false } = options;

  const args = ['pr', 'create', '--title', title, '--body', body, '--base', base];

  if (head) {
    args.push('--head', head);
  }

  if (draft) {
    args.push('--draft');
  }

  const { stdout } = await runCommand('gh', args);
  return stdout.trim();
}

/**
 * Get PR status
 */
// eslint-disable-next-line no-unused-vars
async function getPRStatus(prNumber) {
  const { stdout } = await runCommand('gh', [
    'pr',
    'view',
    String(prNumber),
    '--json',
    'state,mergeable,reviews,statusCheckRollup',
  ]);
  return JSON.parse(stdout);
}

/**
 * List PRs
 */
export async function listPRs(options = {}) {
  const { state = 'open', limit = 10 } = options;

  const args = [
    'pr',
    'list',
    '--state',
    state,
    '--limit',
    String(limit),
    '--json',
    'number,title,headRefName,state,createdAt',
  ];

  const { stdout } = await runCommand('gh', args);
  return JSON.parse(stdout);
}

// ============================================================================
// ISSUE → TASK CONVERSION
// ============================================================================

/**
 * Convert GitHub issue to Ultra-Dex task format
 */
export function issueToTask(issue) {
  // Detect agent from labels
  let agent = '@Planner'; // Default
  for (const label of issue.labels || []) {
    const labelName = label.name?.toLowerCase() || label.toLowerCase();
    if (GITHUB_CONFIG.labelToAgent[labelName]) {
      agent = GITHUB_CONFIG.labelToAgent[labelName];
      break;
    }
  }

  return {
    id: `gh-${issue.number}`,
    source: 'github',
    issueNumber: issue.number,
    title: issue.title,
    description: issue.body || '',
    agent,
    labels: (issue.labels || []).map((l) => l.name || l),
    createdAt: issue.createdAt,
    status: 'pending',
  };
}

/**
 * Sync issues to local task file
 */
export async function syncIssuesToTasks(workdir = process.cwd()) {
  const stateFile = path.join(workdir, GITHUB_CONFIG.stateFile);

  // Load existing state
  let state = { syncedIssues: {}, lastSync: null };
  try {
    state = JSON.parse(await fs.readFile(stateFile, 'utf8'));
  } catch {
    // No existing state
  }

  // Fetch open issues
  const issues = await listIssues({ limit: 50 });

  // Convert to tasks
  const tasks = issues.map(issueToTask);

  // Track which issues we've synced
  const newTasks = [];
  for (const task of tasks) {
    if (!state.syncedIssues[task.id]) {
      newTasks.push(task);
      state.syncedIssues[task.id] = {
        syncedAt: new Date().toISOString(),
        issueNumber: task.issueNumber,
      };
    }
  }

  // Save state
  state.lastSync = new Date().toISOString();
  await fs.mkdir(path.dirname(stateFile), { recursive: true });
  await fs.writeFile(stateFile, JSON.stringify(state, null, 2));

  return { all: tasks, new: newTasks };
}

// ============================================================================
// AUTO-PR CREATION
// ============================================================================

/**
 * Create PR from swarm output
 */
export async function createPRFromSwarm(swarmResult, options = {}) {
  const { branch = null, title = null, draft = true } = options;

  // Generate branch name
  const branchName = branch || `ultra-dex/${Date.now()}`;

  // Create branch
  await runCommand('git', ['checkout', '-b', branchName]);

  // Stage all changes
  await runCommand('git', ['add', '-A']);

  // Commit
  const commitMsg = swarmResult.goal || 'Ultra-Dex agent swarm implementation';
  await runCommand('git', ['commit', '-m', commitMsg]);

  // Push
  await runCommand('git', ['push', '-u', 'origin', branchName]);

  // Generate PR body
  const prBody = GITHUB_CONFIG.prTemplate
    .replace('{summary}', swarmResult.goal || 'Automated implementation')
    .replace('{changes}', swarmResult.artifacts?.join('\n- ') || 'See commits for details')
    .replace('{testing}', '- [ ] Manual testing\n- [ ] Automated tests pass');

  // Create PR
  const prTitle = title || `🤖 ${commitMsg}`;
  const prUrl = await createPullRequest(prTitle, prBody, { head: branchName, draft });

  return { branch: branchName, prUrl };
}

// ============================================================================
// WEBHOOK HANDLER (for CI integration)
// ============================================================================

/**
 * Parse GitHub webhook payload
 */
export function parseWebhook(payload) {
  if (payload.action === 'opened' && payload.issue) {
    return {
      type: 'issue_opened',
      issue: issueToTask(payload.issue),
    };
  }

  if (payload.action === 'completed' && payload.workflow_run) {
    return {
      type: 'workflow_completed',
      workflow: payload.workflow_run,
      success: payload.workflow_run.conclusion === 'success',
    };
  }

  if (payload.action === 'submitted' && payload.review) {
    return {
      type: 'pr_review',
      pr: payload.pull_request,
      review: payload.review,
      approved: payload.review.state === 'approved',
    };
  }

  return { type: 'unknown', payload };
}

// ============================================================================
// CLI COMMAND
// ============================================================================

export function registerGitHubCommand(program) {
  program
    .command('github')
    .description('GitHub integration for issues, PRs, and CI/CD')
    .option('--sync', 'Sync GitHub issues to local tasks')
    .option('--issues', 'List open issues')
    .option('--prs', 'List open pull requests')
    .option('--create-issue <title>', 'Create a new issue')
    .option('--create-pr', 'Create PR from current changes')
    .option('--status', 'Check GitHub CLI status')
    .option('--labels <labels>', 'Filter by labels (comma-separated)')
    .option('--draft', 'Create PR as draft')
    .action(async (options) => {
      logger.log(chalk.cyan('\n🐙 Ultra-Dex GitHub Integration\n'));

      // Check GitHub CLI
      const spinner = ora('Checking GitHub CLI...').start();
      const ghStatus = await checkGitHubCLI();

      if (!ghStatus.installed) {
        spinner.fail('GitHub CLI (gh) not installed');
        logger.log(chalk.yellow('\nInstall: https://cli.github.com/'));
        return;
      }

      if (!ghStatus.authenticated) {
        spinner.fail('Not authenticated with GitHub');
        logger.log(chalk.yellow('\nRun: gh auth login'));
        return;
      }

      spinner.succeed('GitHub CLI ready');

      // Get repo info
      const repo = await getRepoInfo();
      if (!repo) {
        logger.log(chalk.yellow('\n⚠️  Not in a GitHub repository'));
        return;
      }

      logger.log(chalk.gray(`Repository: ${repo.owner.login}/${repo.name}\n`));

      try {
        if (options.status) {
          // Just show status (already done above)
          logger.log(chalk.green('✅ GitHub integration active'));
          return;
        }

        if (options.issues) {
          // List issues
          spinner.start('Fetching issues...');
          const labelFilter = options.labels?.split(',') || [];
          const issues = await listIssues({ labels: labelFilter });
          spinner.succeed(`Found ${issues.length} open issues\n`);

          if (issues.length === 0) {
            logger.log(chalk.gray('No open issues found.'));
            return;
          }

          for (const issue of issues) {
            const labels = (issue.labels || []).map((l) => chalk.cyan(`[${l.name}]`)).join(' ');
            logger.log(`#${chalk.bold(issue.number)} ${issue.title} ${labels}`);
          }
          return;
        }

        if (options.prs) {
          // List PRs
          spinner.start('Fetching pull requests...');
          const prs = await listPRs();
          spinner.succeed(`Found ${prs.length} open PRs\n`);

          for (const pr of prs) {
            logger.log(
              `#${chalk.bold(pr.number)} ${pr.title} ${chalk.gray(`(${pr.headRefName})`)}`
            );
          }
          return;
        }

        if (options.sync) {
          // Sync issues to tasks
          spinner.start('Syncing issues to tasks...');
          const result = await syncIssuesToTasks();
          spinner.succeed(`Synced ${result.all.length} issues (${result.new.length} new)\n`);

          if (result.new.length > 0) {
            logger.log(chalk.bold('New tasks:'));
            for (const task of result.new) {
              logger.log(`  ${task.agent} #${task.issueNumber}: ${task.title}`);
            }
          }
          return;
        }

        if (options.createIssue) {
          // Create issue
          const { body } = await inquirer.prompt([
            {
              type: 'editor',
              name: 'body',
              message: 'Issue description:',
            },
          ]);

          spinner.start('Creating issue...');
          const url = await createIssue(options.createIssue, body);
          spinner.succeed(`Issue created: ${url}`);
          return;
        }

        if (options.createPr) {
          // Create PR from current changes
          const { title, description } = await inquirer.prompt([
            { type: 'input', name: 'title', message: 'PR title:' },
            { type: 'editor', name: 'description', message: 'PR description:' },
          ]);

          spinner.start('Creating pull request...');

          const prBody = GITHUB_CONFIG.prTemplate
            .replace('{summary}', description)
            .replace('{changes}', 'See commits for details')
            .replace('{testing}', '- [ ] Tests pass\n- [ ] Manual testing');

          const url = await createPullRequest(title, prBody, { draft: options.draft });
          spinner.succeed(`Pull request created: ${url}`);
          return;
        }

        // Default: show menu
        const { action } = await inquirer.prompt([
          {
            type: 'list',
            name: 'action',
            message: 'What would you like to do?',
            choices: [
              { name: '📋 List open issues', value: 'issues' },
              { name: '🔀 List open PRs', value: 'prs' },
              { name: '🔄 Sync issues to tasks', value: 'sync' },
              { name: '➕ Create new issue', value: 'create-issue' },
              { name: '🚀 Create PR from changes', value: 'create-pr' },
              { name: '❌ Cancel', value: 'cancel' },
            ],
          },
        ]);

        // Recurse with selected action
        if (action !== 'cancel') {
          logger.log(
            chalk.gray(
              `Re-run with --${action} to execute this action non-interactively (menu recursion disabled).`
            )
          );
        }
      } catch (err) {
        spinner.fail(`Failed: ${err.message}`);
      }
    });
}

export default {
  registerGitHubCommand,
  checkGitHubCLI,
  listIssues,
  listPRs,
  createIssue,
  createPullRequest,
  createPRFromSwarm,
  syncIssuesToTasks,
  parseWebhook,
};
