#!/usr/bin/env sh
set -eu

ROOT_DIR="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT_DIR"

STATUS_DIR="gitFail/compliance/status"
mkdir -p "$STATUS_DIR"

STAMP="$(date -u +"%Y-%m-%dT%H-%M-%SZ")"
REPORT_PATH="$STATUS_DIR/daily-safety-$STAMP.md"
FAIL_COUNT=0

append_cmd_output() {
  LABEL="$1"
  shift

  echo "## $LABEL" >> "$REPORT_PATH"
  echo '```text' >> "$REPORT_PATH"

  set +e
  OUTPUT=$("$@" 2>&1)
  CODE=$?
  set -e

  # Only write output if it exists and is not just whitespace
  if [ -n "$(echo "$OUTPUT" | tr -d '[:space:]')" ]; then
    echo "$OUTPUT" >> "$REPORT_PATH"
  else
    echo "(command produced no output)" >> "$REPORT_PATH"
  fi

  echo '```' >> "$REPORT_PATH"
  echo "Exit code: $CODE" >> "$REPORT_PATH"
  echo >> "$REPORT_PATH"

  if [ "$CODE" -eq 0 ]; then
    echo "[daily-safety] PASS: $LABEL"
  else
    echo "[daily-safety] FAIL: $LABEL (exit $CODE)"
    FAIL_COUNT=$((FAIL_COUNT + 1))
  fi
}

append_info_output() {
  LABEL="$1"
  shift

  echo "## $LABEL" >> "$REPORT_PATH"
  echo '```text' >> "$REPORT_PATH"

  set +e
  "$@" >> "$REPORT_PATH" 2>&1
  CODE=$?
  set -e

  echo '```' >> "$REPORT_PATH"
  echo "Exit code: $CODE (informational)" >> "$REPORT_PATH"
  echo >> "$REPORT_PATH"

  if [ "$CODE" -eq 0 ]; then
    echo "[daily-safety] INFO: $LABEL passed."
  else
    echo "[daily-safety] INFO: $LABEL blocked (expected during suspension)."
  fi
}

cat > "$REPORT_PATH" <<EOF
# Daily Safety Check Report

Timestamp (UTC): $STAMP
Repository: $(basename "$ROOT_DIR")

This report is generated by:
\`gitFail/compliance/daily-safety-check.sh\`

EOF

append_cmd_output "Git Status" git status --short --branch
append_cmd_output "Recent Commits" git --no-pager log --oneline -n 10
append_cmd_output "Governance Files Check" node gitFail/compliance/check-governance-files.js
append_cmd_output "Local Enterprise Gate" npm run -s gate:local
append_info_output "Remote Guard Check" npm run -s guard:github
append_cmd_output "Support Evidence Snapshot" sh gitFail/compliance/capture-support-evidence.sh

{
  echo "## Summary"
  if [ "$FAIL_COUNT" -eq 0 ]; then
    echo "- Local readiness: PASS"
  else
    echo "- Local readiness: FAIL ($FAIL_COUNT check(s) failed)"
  fi
  echo "- Report file: \`$REPORT_PATH\`"
} >> "$REPORT_PATH"

echo "[daily-safety] Report written to $REPORT_PATH"

if [ "$FAIL_COUNT" -ne 0 ]; then
  exit 1
fi

