// Copyright (c) 2026 Ultra-Dex

// Copyright (c) 2026 Ultra-Dex

/**
 * Cursor 2.0 Integration for ACP
 * Provides Cursor IDE-specific configuration and tools
 */

import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import chalk from 'chalk';
import { printInfo, printSuccess, printWarning } from '../utils/output.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/**
 * Cursor IDE integration class
 */
export class CursorIntegration {
  constructor(projectPath = process.cwd()) {
    this.projectPath = projectPath;
    this.cursorDir = path.join(projectPath, '.cursor');
    this.acpConfigPath = path.join(this.cursorDir, 'acp.json');
  }

  /**
   * Generate Cursor 2.0 configuration for ACP
   */
  async generateConfig(options = {}) {
    const config = {
      version: '2.0',
      acp: {
        enabled: true,
        protocolVersion: '0.10.8',
        host: {
          command: 'ultra-dex',
          args: ['--acp'],
          stdio: 'pipe',
          env: {
            FORCE_COLOR: '3',
          },
        },
        capabilities: {
          text: true,
          images: false,
          audio: false,
          terminal: true,
          filesystem: {
            read: true,
            write: true,
          },
        },
      },
      context: {
        ultraDex: {
          enabled: true,
          contextFile: 'CONTEXT.md',
          autoSync: true,
        },
        include: ['README.md', 'package.json', 'tsconfig.json', 'CONTEXT.md', 'AGENTS.md'],
        exclude: ['node_modules/**', '.git/**', 'dist/**', 'build/**', 'coverage/**', '*.log'],
      },
      modes: {
        ask: {
          name: 'Ask',
          description: 'General questions and explanations',
          systemPrompt:
            'You are a helpful assistant. Use the Ultra-Dex context to provide accurate information about the project.',
        },
        architect: {
          name: 'Architect',
          description: 'Design and planning mode',
          systemPrompt:
            'You are a software architect. Analyze requirements and create detailed implementation plans. Consider the existing codebase structure and Ultra-Dex guidelines.',
        },
        code: {
          name: 'Code',
          description: 'Implementation mode',
          systemPrompt:
            "You are a software engineer. Write clean, well-documented code following the project's coding standards and Ultra-Dex best practices.",
        },
        review: {
          name: 'Review',
          description: 'Code review mode',
          systemPrompt:
            'You are a code reviewer. Analyze code for bugs, security issues, and improvements. Be thorough and constructive.',
        },
        test: {
          name: 'Test',
          description: 'Testing mode',
          systemPrompt:
            "You are a QA engineer. Write comprehensive tests and help debug issues. Follow the project's testing conventions.",
        },
      },
      tools: {
        ultraDex: {
          commands: {
            sync: {
              description: 'Sync Ultra-Dex context',
              command: 'ultra-dex sync --brain',
            },
            plan: {
              description: 'Generate implementation plan',
              command: 'ultra-dex plan',
            },
            validate: {
              description: 'Validate project state',
              command: 'ultra-dex validate',
            },
            swarm: {
              description: 'Run agent swarm',
              command: 'ultra-dex swarm',
            },
          },
        },
      },
      ...options,
    };

    return config;
  }

  /**
   * Install Cursor 2.0 ACP configuration
   */
  async install() {
    printInfo('Installing Cursor 2.0 ACP integration...');

    try {
      // Create .cursor directory if it doesn't exist
      await fs.mkdir(this.cursorDir, { recursive: true });

      // Generate and write ACP config
      const config = await this.generateConfig();
      await fs.writeFile(this.acpConfigPath, JSON.stringify(config, null, 2), 'utf8');

      // Create rules file for Cursor
      const rulesContent = this.generateRulesFile();
      await fs.writeFile(path.join(this.cursorDir, 'rules'), rulesContent, 'utf8');

      printSuccess('✅ Cursor 2.0 ACP integration installed');
      printInfo(`   Config: ${this.acpConfigPath}`);
      printInfo(`   Rules: ${path.join(this.cursorDir, 'rules')}`);

      return config;
    } catch (error) {
      throw new Error(`Failed to install Cursor integration: ${error.message}`);
    }
  }

  /**
   * Generate Cursor rules file content
   */
  generateRulesFile() {
    return `# Ultra-Dex + Cursor 2.0 ACP Integration Rules
# Auto-generated by Ultra-Dex

## Context Awareness
- Always check CONTEXT.md for project context before making changes
- Follow the tech stack and architecture defined in the context
- Respect key decisions documented in the project

## Code Quality
- Run validation before committing: ultra-dex validate
- Follow the project's linting and formatting rules
- Ensure tests pass before considering work complete

## Workflow Integration
- Use ultra-dex sync --brain to keep context updated
- Check implementation plans before starting work
- Update CONTEXT.md when making architectural changes

## Security
- Never commit secrets or API keys
- Follow security best practices defined in the project
- Run security audits regularly

## ACP Protocol
- This project supports Agent Client Protocol v0.10.8
- Use --acp flag to start ACP host for IDE integration
- Available modes: ask, architect, code, review, test
`;
  }

  /**
   * Generate VS Code settings for Cursor compatibility
   */
  async generateVSCodeSettings() {
    const settings = {
      'cursor.acp.enabled': true,
      'cursor.acp.host': 'stdio',
      'cursor.acp.command': 'ultra-dex --acp',
      'cursor.context.files': ['CONTEXT.md', 'README.md', 'package.json'],
      'cursor.tools.ultradex.enabled': true,
      'cursor.tools.ultradex.syncOnSave': true,
    };

    const vscodeDir = path.join(this.projectPath, '.vscode');
    await fs.mkdir(vscodeDir, { recursive: true });

    const settingsPath = path.join(vscodeDir, 'settings.json');

    // Merge with existing settings if present
    let existingSettings = {};
    try {
      const existing = await fs.readFile(settingsPath, 'utf8');
      existingSettings = JSON.parse(existing);
    } catch {
      // File doesn't exist or is invalid
    }

    const mergedSettings = { ...existingSettings, ...settings };

    await fs.writeFile(settingsPath, JSON.stringify(mergedSettings, null, 2), 'utf8');

    printSuccess('✅ VS Code settings updated for Cursor compatibility');
    return mergedSettings;
  }

  /**
   * Uninstall Cursor integration
   */
  async uninstall() {
    printInfo('Uninstalling Cursor 2.0 ACP integration...');

    try {
      await fs.unlink(this.acpConfigPath).catch(() => {});
      await fs.unlink(path.join(this.cursorDir, 'rules')).catch(() => {});

      // Try to remove .cursor directory if empty
      try {
        const files = await fs.readdir(this.cursorDir);
        if (files.length === 0) {
          await fs.rmdir(this.cursorDir);
        }
      } catch {
        // Directory not empty or doesn't exist
      }

      printSuccess('✅ Cursor 2.0 ACP integration uninstalled');
    } catch (error) {
      throw new Error(`Failed to uninstall Cursor integration: ${error.message}`);
    }
  }

  /**
   * Check if Cursor integration is installed
   */
  async isInstalled() {
    try {
      await fs.access(this.acpConfigPath);
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Get current configuration
   */
  async getConfig() {
    try {
      const content = await fs.readFile(this.acpConfigPath, 'utf8');
      return JSON.parse(content);
    } catch {
      return null;
    }
  }

  /**
   * Update configuration
   */
  async updateConfig(updates) {
    const config = (await this.getConfig()) || (await this.generateConfig());
    const updated = { ...config, ...updates };

    await fs.writeFile(this.acpConfigPath, JSON.stringify(updated, null, 2), 'utf8');

    return updated;
  }
}

/**
 * CLI command handler for Cursor integration
 */
export async function cursorCommand(options) {
  const integration = new CursorIntegration();

  if (options.uninstall) {
    await integration.uninstall();
    return;
  }

  if (options.status) {
    const installed = await integration.isInstalled();
    if (installed) {
      const config = await integration.getConfig();
      printInfo('Cursor 2.0 ACP Integration Status:');
      printInfo(`   Installed: Yes`);
      printInfo(`   Version: ${config?.version || 'unknown'}`);
      printInfo(`   ACP Enabled: ${config?.acp?.enabled ? 'Yes' : 'No'}`);
      printInfo(`   Protocol Version: ${config?.acp?.protocolVersion || 'unknown'}`);
    } else {
      printWarning('Cursor 2.0 ACP integration is not installed');
      printInfo('Run "ultra-dex cursor --install" to install');
    }
    return;
  }

  if (options.vscode) {
    await integration.generateVSCodeSettings();
    return;
  }

  // Default: install
  await integration.install();

  if (options.vscode) {
    await integration.generateVSCodeSettings();
  }
}

export default CursorIntegration;
